### ISSUE TITLE
Change panel priority in runtime.

### ISSUE THREAD

**Issue by sgamerw** [yankooliveira/uiframework#1]
Great job, I have learned a lot from this project and your blog and thank you for your great work. Up to now, I still have a question. 
I download and play **`Blood runs cold`**, **`Axon`** and  **`Hocus Puzzle`**, in **`Hocus Puzzle`**, the top resource panel is under the level window, when I click add Runes button, Runes window opened and resource panel show on the top, so the resource panel changed priority dynamic or current resource panel is another same one just show on the top priority level?

![2001564041999_.pic.jpg](https://i.loli.net/2019/07/25/5d3963262d5f277033.jpg)
![2011564042000_.pic.jpg](https://i.loli.net/2019/07/25/5d3963265458f96516.jpg)
![2021564042001_.pic.jpg](https://i.loli.net/2019/07/25/5d3963265f54f95601.jpg)

**Comment by yankooliveira** [comment]
Hey there! Glad that it helped!

Even though there was a similar architecture used in Blood Runs Cold, it wasn't used on any of the other games you mentioned, so I can't say how exactly they achieved that. But since you gave me some screenshots, I could understand the use case so I can give you some pointers if you were to do the same in this system.

It seems like level and runes would be 2 popups (as the darkening of the previous screen is automatic using popups, and the examples you gave seem to be modal).

The bar on the top would be indeed a panel, but the framework doesn't support runtime panel priority changes. That means that you would either have a copy of the bar on the runes popup (which is done pretty easily now that Unity has nested prefabs), or you'd have to add that functionality yourself.

Given that priority is simply parenting the element to another object in the hierarchy, and panels don't have history or any relation to each other, it should be safe to do it at any point; you'd just have to add a function in `PanelUILayer` to change the priority of a given panel - you could even just call `ReparentScreen()` passing it's controller and it's transform after having changed the priority in the panel's properties.

You'd just need to decide your "entry point" for that request: if it's the panel itself requesting the change, you could use the same event pattern as `CloseRequest` (used by the window's `UI_Close()` method), or you can make a function on the `UIFrame` itself that passes the command down to the Panel layer.

In any way you implement it, you should make sure the type is set on the Panel's properties to guarantee consistency and to allow for easy inspection.

**Comment by sgamerw** [comment]
Thanks a lot, it makes things clearer in my head.
